/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KSEB;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author nyesteventuretechnologies
 */
public class GenerateBill extends javax.swing.JFrame {
   
    double name,name1,name2,name3;
    /**
     * Creates new form GenerateBill
     */
    public GenerateBill() {
        initComponents();
         this.setBounds(200, 100, 526, 521);
        this.setResizable(false);
        try {
            Database d=new Database();
            //int consumer = d.rs.getInt(1);
            String sql = "select * from register";
            d.ps = d.con.prepareStatement(sql);
             //d.ps.setInt(1, consumer);
            d.rs = d.ps.executeQuery();
            while (d.rs.next()) {
                String consumer = d.rs.getString("consumer");
                jComboBox1.addItem(consumer);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select Manufacturer");
            System.out.println("Error in combobox" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("GENERATE BILL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 20, 160, 14);

        jLabel4.setText("Counsumer No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 90, 100, 14);

        jLabel5.setText("From Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 140, 100, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 140, 200, 30);

        jLabel6.setText("To Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 200, 90, 14);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 190, 200, 30);

        jLabel7.setText("Unit Consumed");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 260, 110, 14);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 250, 200, 30);

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 430, 110, 40);

        jLabel3.setText("Due Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 310, 100, 20);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 70, 200, 50);

        jLabel8.setText("Disconnection");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 360, 120, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 306, 200, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(210, 360, 200, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KSEB/b_home.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 430, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KSEB/image.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 // TODO add your handling code here:
    
    try
    {
       Database d=new Database();
       String consumer =(String) jComboBox1.getSelectedItem();
       String fromdate=jTextField2.getText();
       String todate=jTextField3.getText();
       String unit=jTextField4.getText();
       double i=Double.parseDouble(unit);
        System.out.println("....");
       if(i<50)
       {
           name = i*2.8;
           System.out.println(name);
       }  
           else if(i>50)
           {
              name1=i*3.2;
               System.out.println(name1);
           }
           
       else
       {
           System.out.println("85");
       }
       double name2=name+name1+name3;
        System.out.println(name2);
       //int j=Integer.parseInt(jTextField1.getText());
       String due=jTextField1.getText();
       String disconnect=jTextField5.getText();
      
        
       PreparedStatement ps=d.con.prepareStatement("insert into bill (consumer,fromdate,todate,unit,amount,due,disconnect)values(?,?,?,?,?,?,?)");
        System.out.println("=====");
       ps.setString(1, consumer);
       ps.setString(2, fromdate);
       ps.setString(3, todate);
       ps.setDouble(4, i);
       ps.setDouble(5, name2);
       ps.setString(6, due);
       ps.setString(7, disconnect);
       int val=ps.executeUpdate();
        if(val>=1)
        {
            JOptionPane.showMessageDialog(this, "Successsfully stored..");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "error in stored..");
        }
        
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Admin a=new Admin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
